### PR TITLE
Fix invalid scheme error with Addressable::Template

### LINKED ISSUE #489: Invalid scheme format. (Addressable::URI::InvalidURIError)
Hi,

i get the Invalid scheme format. (Addressable::URI::InvalidURIError) error when i use templates with Webmock. i traced the error down this this line https://github.com/bblimke/webmock/blob/master/lib/webmock/request_pattern.rb#L136

`uri = "http://127.0.0.1:50153/__identify__"`
and where 
`WebMock::Util::URI.variations_of_uri_as_strings(uri)`
creates the following array:
`["http://127.0.0.1:50160/__identify__", "127.0.0.1:50160/__identify__"]`
passing that to `any?` where the `@pattern.match(u)` throws the exception when comparing with the second element from the hash.

i looked up `WebMock::Util::URI.variations_of_uri_as_strings(uri)` and it creates them on purpose.

```
if normalized_uri.scheme == "http"
  uris = uris_with_scheme_and_without(uris)
end
```

so i assume that array of URI's is correct. what other thing could go wrong here?
can you point me at something to debug?

_UPDATE_

thats not the URI i want to template.

```
bitbucket_uri = Addressable::Template.new("https://bitbucket.org/api/1.0/repositories/codeship/{bitbucket_repo_name}/services")
  WebMock.stub_request(:get, bitbucket_uri).
    to_return(status: 200)
```

i guess thats coming from some other tool in our cucumber suite. but if i remove any template from Webmock, the error is gone.
thanks
ben

### PR DESCRIPTION
**Pull request by uiureo**
Fix #489 

# problem
`Addressable::Template#match` expects a valid uri with scheme
  https://github.com/sporkmonger/addressable/issues/208#issuecomment-162404607

It works with most cases without uri scheme, but it raises an error with some cases like `127.0.0.1:8080`.

I've found that it causes the error when using webmock with [System Spec](https://relishapp.com/rspec/rspec-rails/docs/system-specs/system-spec) and chrome driver.

# solution
Always pass a uri with scheme to `Addressable::Template#match`. 

The difference from #739 is 
- adding a spec 
- making failing specs pass

### CODE REVIEW

**Comment by bblimke** [comment]
@uiureo thank you for the PR.

Could you please explain why have you removed all these urls in https://github.com/bblimke/webmock/pull/758/files#diff-a5f6621858e36a69278262b16c576604 ?

These urls were there to guarantee that WebMock can match urls without scheme provided with urls with the default scheme, which is not the case anymore.
As I understand this change breaks backwards compatibility?

**Comment by uiureo** [comment]
Ah I understand. This is mistake.
I will fix it in a way that it doesn't change `WebMock::Util::URI.variations_of_uri_as_strings`.

**Comment by uiureo** [comment]
Added `with_scheme: true` option to `WebMock::Util::URI.variations_of_uri_as_strings` instead.

@bblimke How do you think?

File: lib/webmock/util/uri.rb [hunk 1]
```diff
@@ -47,7 +47,7 @@ def self.variations_of_uri_as_strings(uri_object)
           uris = uris_with_inferred_port_and_without(uris)
         end
 
-        if normalized_uri.scheme == "http"
+        if normalized_uri.scheme == "http" && !with_scheme
```
Comment (bblimke) [inline lib/webmock/util/uri.rb]: I'm not sure I understand the with_scheme flag here. The condition is "if not with scheme" and the line below compares returns values with scheme and without.

Comment (uiureo) [reply lib/webmock/util/uri.rb]: The flag means "returns only variations with scheme", but I agree it's confusing.

`only_variations_with_scheme` might be better?

Comment (bblimke) [reply lib/webmock/util/uri.rb]: Yes `only_with_scheme` would be more meaningful.

Comment (uiureo) [reply lib/webmock/util/uri.rb]: updated https://github.com/bblimke/webmock/pull/758/commits/19624000ba9701ade80df97a5d92d3bc3c2ca4a6

**Comment by uiureo** [comment]
@bblimke Could you review this again?

**Comment by bblimke** [comment]
@uiureo sorry. Looks good. Thank you!

**Comment by bblimke** [comment]
Released as 3.4.2. Thank you!

**Comment by alain-andre** [comment]
Hi there, I'm having this issue and I'm wondering why I cannot see this fix in the latest code : https://github.com/bblimke/webmock/blob/904aa9806a91fb292a142dc2783ff762eacca0d8/lib/webmock/request_pattern.rb#L190
It has been remove on [commit](https://github.com/bblimke/webmock/commit/8b1414850ed5b031bba0c21b1033058c4725ff2f)

I do not understand why in the UT it adds the `only_with_scheme` of the `WebMock::Util::URI.variations_of_uri_as_strings` method but removes it from the `request_pattern` class.

Any idea ?

**Comment by bblimke** [comment]
@alain-andre it has been removed due to this issue https://github.com/bblimke/webmock/issues/828 

The problem was that the only_with_scheme solution is not complete.

Hopefully the issue will be resolved once https://github.com/bblimke/webmock/pull/890 is finished. @guppy0356
